name: Android CI

on:
  push:
    branches: [ main, "codex/**", "feature/**" ]
  pull_request:
  workflow_dispatch:
    inputs:
      args:
        description: "Gradle arguments"
        required: false
        default: ":app:assembleDebug :app:testDebugUnitTest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Gradle Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ${{ inputs.args || ':app:assembleDebug :app:testDebugUnitTest' }}

      - name: Upload reports (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/**
            **/build/test-results/**
          if-no-files-found: ignore
